apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  type: LoadBalancer
  ports:
    - targetPort: 50050
      port: 50050
      protocol: TCP
      name: http

  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: demo-frontend
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: prod
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        env: prod

    spec:
      containers:
        - name: frontend
          image: gcr.io/b3inject/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 50050
